// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5aLlYtW2gCh7e2zpXUwKihgxT-WRH_A',
    appId: '1:845060610722:web:f1ddd726dfc52158be55fb',
    messagingSenderId: '845060610722',
    projectId: 'receptscanner-2878a',
    authDomain: 'receptscanner-2878a.firebaseapp.com',
    storageBucket: 'receptscanner-2878a.firebasestorage.app',
    measurementId: 'G-K8LL7EQX7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Os-iG-DPaGZnuC1P2opW5TAy61LU_f8',
    appId: '1:845060610722:android:5f2d97e988289f54be55fb',
    messagingSenderId: '845060610722',
    projectId: 'receptscanner-2878a',
    storageBucket: 'receptscanner-2878a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2yMtRUrrq19LSGtn6CU-6TbzC_GWcwI',
    appId: '1:845060610722:ios:a8cf06bfb5f8507fbe55fb',
    messagingSenderId: '845060610722',
    projectId: 'receptscanner-2878a',
    storageBucket: 'receptscanner-2878a.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2yMtRUrrq19LSGtn6CU-6TbzC_GWcwI',
    appId: '1:845060610722:ios:a8cf06bfb5f8507fbe55fb',
    messagingSenderId: '845060610722',
    projectId: 'receptscanner-2878a',
    storageBucket: 'receptscanner-2878a.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV5aLlYtW2gCh7e2zpXUwKihgxT-WRH_A',
    appId: '1:845060610722:web:642ddb75a8397db3be55fb',
    messagingSenderId: '845060610722',
    projectId: 'receptscanner-2878a',
    authDomain: 'receptscanner-2878a.firebaseapp.com',
    storageBucket: 'receptscanner-2878a.firebasestorage.app',
    measurementId: 'G-E5MG3BMFZ2',
  );
}
